# --- Project metadata
[project]
name = "classroom-cli"      # used for pip/uv/pipx install commands
version = "0.2.0"
description = "CLI for managing GitHub assignments"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name="Devon Lantagne", email="lantagned@msoe.edu" }
]
dependencies = [
    "click",
    "PyGithub",
    "pandas"
]

# --- Commands created on install
[project.scripts]
clsrm = "classroom_cli.cli:cli"

# --- How to build/install the package
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# --- Where setuptools finds code
# Explicit include avoids "multiple top-level packages" errors
[tool.setuptools.packages.find]
include = ["classroom_cli*"]
